#org.gradle.java.home=C\:/Program Files/Android/Android Studio/jbr
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64
android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx2048m -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=512m"
org.gradle.workers.max=1
org.gradle.priority=low
org.gradle.parallel=false
